[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ff0050"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#fafafa"
