[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#007AFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1C1C1E"
textColor = "#F5F5F7"
font = "sans serif"
